First Commit
gaurav-unifydots/Automation pull request #1
Opened 2023-12-18 13:02 UTC by gaurav-unifydots

2023-12-19 04:12 UTC, vivek-unifydots requested changes
@gaurav-unifydots please address the comments

2023-12-19 07:27 UTC, gaurav-unifydots commented on .idea/.gitignore
> +# Default ignored files
done

2023-12-19 07:29 UTC, gaurav-unifydots commented on lib/jcommander-1.48.jar
done

2023-12-19 07:29 UTC, gaurav-unifydots commented on lib/jcommander-1.48.jar
done

2023-12-19 07:31 UTC, gaurav-unifydots commented on pom.xml
> +		<dependency>
done

2023-12-19 07:31 UTC, gaurav-unifydots commented on pom.xml
> +			<id>maven.oracle.com</id>
removed

2023-12-19 07:31 UTC, gaurav-unifydots commented on pom.xml
> +
removed

2023-12-19 07:38 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +        //Assert.assertFalse(true);
done

2023-12-19 07:38 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +    public void afterSuite(){ //executed after all the tests have ran
done

2023-12-19 07:39 UTC, gaurav-unifydots commented on src/test/resources/testng.xml
> +    <!--<listeners>
done

2023-12-19 07:39 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/SecondTest.java
> +        //Assert.assertFalse(true);
done

2023-12-19 08:11 UTC, vivek-unifydots commented on .gitignore.bak
> +target/
please remove this file

2023-12-19 08:12 UTC, vivek-unifydots commented on .idea/workspace.xml
please remove .idea folder from commit

2023-12-19 08:12 UTC, vivek-unifydots commented on allure-results/03472a10-e11f-48c5-acf8-680498cce8d9-container.json
please do not include results into commit

2023-12-19 08:13 UTC, vivek-unifydots commented on pom.xml
> +        <dependency>
please remove unused dependencies

2023-12-19 08:14 UTC, vivek-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +    public ExtentReports extent = new ExtentReports();
please remove extent report code

2023-12-19 08:15 UTC, vivek-unifydots commented on src/test/java/com/unifydots/tests/SecondTest.java
> +        driver.findElement(By.xpath("//[@email='email']")).sendKeys("gaurav");
locators should be part of page classes

2023-12-19 08:39 UTC, gaurav-unifydots commented on .gitignore.bak
> +target/
done

2023-12-19 08:40 UTC, gaurav-unifydots commented on .idea/workspace.xml
done

2023-12-19 08:41 UTC, gaurav-unifydots commented on allure-results/03472a10-e11f-48c5-acf8-680498cce8d9-container.json
done

2023-12-19 08:42 UTC, gaurav-unifydots commented on pom.xml
> +        <dependency>
done

2023-12-19 08:43 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +    public ExtentReports extent = new ExtentReports();
done

2023-12-19 08:44 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/SecondTest.java
> +        driver.findElement(By.xpath("//[@email='email']")).sendKeys("gaurav");
this was for testing purpose.I will make page class and move it there

2023-12-19 11:40 UTC, vivek-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public void login() throws InterruptedException {
https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

2023-12-19 11:41 UTC, vivek-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public void login() throws InterruptedException {
pass username and password as parameters

2023-12-19 11:42 UTC, vivek-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +loginPage.login();
fix formatting

2023-12-19 11:44 UTC, vivek-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public void login1(){
please remove

2023-12-19 11:46 UTC, vivek-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public  void shutDown(){
@AfterTest or @AfterClass

2023-12-19 11:47 UTC, vivek-unifydots commented on src/main/java/com/unifydots/utility/BaseTest.java
> +package com.unifydots.utility;
java/com/unifydots/tests/base

2023-12-19 11:51 UTC, vivek-unifydots commented on src/main/java/com/unifydots/utility/BaseTest.java
> +	public static EventFiringWebDriver e_driver;
please remove

2023-12-19 11:53 UTC, vivek-unifydots commented on src/test/java/com/unifydots/tests/SecondTest.java
> +loginPage.shutDown();
please fix formatting

2023-12-19 11:54 UTC, vivek-unifydots commented on src/test/resources/testng.xml
> +    <test name="Unify Dots Tests" preserve-order="false" parallel="false" thread-count="2">
fix parallel

2023-12-19 11:55 UTC, vivek-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +
remove extra spaces

2023-12-19 12:48 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +loginPage.login();
done

2023-12-19 12:48 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public  void shutDown(){
done

2023-12-20 05:44 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public void login() throws InterruptedException {
done

2023-12-20 05:44 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +loginPage.login();
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public void login1(){
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public void login1(){
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public  void shutDown(){
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/utility/BaseTest.java
> +package com.unifydots.utility;
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    public  void shutDown(){
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/main/java/com/unifydots/utility/BaseTest.java
> +package com.unifydots.utility;
done

2023-12-20 05:45 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/SecondTest.java
> +loginPage.shutDown();
done

2023-12-20 05:46 UTC, gaurav-unifydots commented on src/test/resources/testng.xml
> +    <test name="Unify Dots Tests" preserve-order="false" parallel="false" thread-count="2">
done

2023-12-20 05:46 UTC, gaurav-unifydots commented on src/test/java/com/unifydots/tests/FirstTest.java
> +
done

2023-12-20 11:10 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    /**
please remove

2023-12-20 11:12 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +         * e_driver = new EventFiringWebDriver(driver); // Now create object of
please remove all this

2023-12-20 11:12 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    public String getTitleOfApplication() {
getTitle()

2023-12-20 11:13 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    public String getCurrentOfApplication() {
getCurrentUrl()

2023-12-20 11:14 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    public String getDateInFormattedString(int offsetFromToday, String format) {
please move this to a new class DateUtils

2023-12-20 11:14 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    public String getDateInFormattedStringMonths(int offsetFromTodayInMonths, String format) {
please move this to a new class DateUtils

2023-12-20 11:15 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    private Date getCurrentDateFromTable(String date) {
from which table this method is getting date

2023-12-20 11:18 UTC, vivek-unifydots commented on unifydots.qa.iml
is this file required to be committed?

2023-12-20 11:21 UTC, vivek-unifydots commented on src/main/java/com/unifydots/base/BaseTest.java
> +    public static void takeScreenshotAtEndOfTest() throws IOException {
from where this method is being called.. this should be part of listener

2023-12-20 11:39 UTC, vivek-unifydots commented on src/main/java/com/unifydots/utility/DateUtils.java
> +    protected Date dateFormatConversion() {
getCurrentDate()

2023-12-20 11:41 UTC, vivek-unifydots commented on src/main/java/com/unifydots/utility/DateUtils.java
> +    private Date getCurrentDateFormat(String date) {
please remove

2023-12-20 11:42 UTC, vivek-unifydots commented on src/test/java/com/unifydots/tests/PropertiesTest.java
> +        System.out.println("base url value from property file "+application.getProperty("base.url"));
Log.info

2023-12-20 11:43 UTC, vivek-unifydots commented on unifydots.qa.iml
please remove

2023-12-20 11:45 UTC, vivek-unifydots commented on src/main/java/com/unifydots/pages/LoginPage.java
> +    @Step
please add description

2023-12-20 11:46 UTC, vivek-unifydots commented on pom.xml
> +                                                <classpathScope>test</classpathScope>
please format or remove

2023-12-20 12:04 UTC, merged